卷积操作

In [2]:
import torch

input = torch.tensor([[1, 2, 0, 3, 1],
                      [2, 1, 4, 0, 2],
                      [3, 0, 1, 2, 3],
                      [4, 3, 2, 1, 4],
                      [5, 4, 3, 2, 5]])

kernel = torch.tensor([[1, 2, 1],
                       [0, 1, 0],
                       [1, 0, -1]])

print(input.shape)
print(kernel.shape)

torch.Size([5, 5])
torch.Size([3, 3])


In [4]:
input = torch.reshape(input, (1, 1, 5, 5))
kernel = torch.reshape(kernel, (1, 1, 3, 3))

print(input.shape)
print(kernel.shape)

torch.Size([1, 1, 5, 5])
torch.Size([1, 1, 3, 3])


In [6]:
import torch.nn.functional as F

output = F.conv2d(input, weight=kernel,  stride=1)
print(output)

output2 = F.conv2d(input, weight=kernel,  stride=2)
print(output2)

tensor([[[[ 8,  7,  5],
          [10, 12,  6],
          [ 9,  8,  7]]]])
tensor([[[[8, 5],
          [9, 7]]]])


In [7]:
output3 = F.conv2d(input, weight=kernel,  stride=1, padding=1)
print(output3)

tensor([[[[ 0,  0,  1,  5,  1],
          [ 6,  8,  7,  5,  9],
          [ 5, 10, 12,  6,  8],
          [ 6,  9,  8,  7, 14],
          [16, 16, 11, 10, 14]]]])


卷积层

In [2]:
import torch
import torchvision
from torch import nn
from torch.utils.data import DataLoader

dataset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=torchvision.transforms.ToTensor())
dataloader = DataLoader(dataset, batch_size=64)

class TuDui(nn.Module):
    def __init__(self):
        super(TuDui, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3, stride=1, padding=0)
        
    def forward(self, x):
        x = self.conv1(x)
        return x

model = TuDui()
print(model)

Files already downloaded and verified
TuDui(
  (conv1): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1))
)


In [6]:
for data in dataloader:
    imgs, targets = data
    output = model(imgs)
    print(imgs.shape)
    print(output.shape)

torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 30, 30])
torch.Size([64, 3, 32, 32])
torch.Size([64, 6, 3

In [8]:
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter(log_dir="logs")
step = 0
for data in dataloader:
    imgs, targets = data
    output = model(imgs)
    # torch.Size([64, 3, 32, 32])
    writer.add_images("input", imgs, step)
    # torch.Size([64, 6, 30, 30])
    output = torch.reshape(output, (-1, 3, 30, 30))
    writer.add_images("output", output, step)
    step += 1

writer.close()